### ISSUE TITLE
CUHK03 camera

### ISSUE THREAD

**Issue by yuedong0607** [KovenYu/DECAMEL#1]
你好！读了camel和decamel的paper感觉很受启发！
想请教一下在cuhk03这个数据集上怎么一一对应的将6个camera ID提取出来
非常感谢！

**Comment by KovenYu** [comment]
@yuedong0607 http://blog.fangchengjin.cn/reid-cuhk03.html 这里的描述非常清晰了

**Comment by yuedong0607** [comment]
感谢回复！有一点不是很理解：这个数据集中摄像头看起来像是按组编号的，每组里有一对，总共5组6个摄像头，有没有办法获得每个bounding box对应的摄像头编号(1-6)呢？

**Comment by KovenYu** [comment]
@yuedong0607 5个pair 总共就是10个camera，后面的4个camera是不用的 所以就是前三个pair每个对应两个camera 总共6个。

**Comment by yuedong0607** [comment]
原来如此！非常感谢，之前一直对这个编号非常疑惑，不是1，2就是1-10。。。
